### ISSUE TITLE
group_by() and rowwise() has to be ungrouped 

### ISSUE THREAD

**Issue by miljukov-o** [nukleus-ecu/epicodr#10]
@nuernbergerc,

group_by() and rowwise() has to be ungrouped before returning the df or else the grouping might persist in the dataframes and cause troubles somewhere else

e.g.
https://github.com/nukleus-ecu/epicodr/blob/a3beecd169e8b38ff71401e97ec6f0f477e4e1f8/R/primary-coding-hap.R#L241

**Comment by nuernbergerc** [comment]
i will check all my code and update it
