### ISSUE TITLE
Consider reverting the changes regarding non-ASCI characters

### ISSUE THREAD

**Issue by miljukov-o** [nukleus-ecu/epicodr#12]
If non-ASCI characters such as umlauts cause trouble, it has to do with your local encoding. If everything is set to UTF-8 correctly, which is the gold standard, then it should not be a problem. There is a reason to use the factor labels explicitly. They should be kept for better readability and to reduce unnecessary comments.

Commit to revert: 29d7585d2181296a43f4aa6b55a0f350b540621c

**Comment by nuernbergerc** [comment]
when i use the factors and with thos non-asci characters, i get the following warning when running devtools::check()
![image](https://user-images.githubusercontent.com/109070680/231112648-6f46ad47-82d8-4df5-95c2-485f83c96ecd.png)
the code however works
i'm just not sure if the pull request will work this way

**Comment by miljukov-o** [comment]
Ok, hmm. I see. Well, it's important for maximum portability but shouldn't limit the execution if we keep the umlauts. 
Here is the suggestion how to handle non-ASCI, but would cause a bit of editing:
https://r-pkgs.org/R-CMD-check.html#r-code
