### ISSUE TITLE
ecu_who_scale table (and other additional created tables) won't be exported with write_tsExport

### ISSUE THREAD

**Issue by mrainers** [nukleus-ecu/epicodr#17]
### Description

The ecu_who_scale table that is created by the `primary_coding_suep()` function is added to the `data` object, but when the write_tsExport function is used to export the data, then this table won't exported.

This is because the write_tsExport function only exports tables that are in `export_options$data_names` list. And the  `primary_coding_suep()` does not update this list.

### Steps to Reproduce

1. read transferoffice export SÜP data with read_tsExport() 
2. run `primary_coding_suep()`
3. export the primary coded dataset that includes a newlie created table "ecu_who_scale" with the `write_tsExport` function.

**Expected behavior**

All data tables that the tsExport data objects contains should be exported.

**Actual behavior**

Only table names that where in the original data set and that are therefor listed in `data$export_options$data_names` will be exported.

**Reproducibility**

I reproduced this Issue with data from `tsExport_Testdata_SUEP_2022-06-27.zip`.

### Additional Information

Two possible solutions come into mind.

1. The primary_coding function updates `data$export_options$data_names` list, when it creates a new table, so that this table will be exported with the write function.
2. Change the write function, so that it will export all tables in the data object regardless if they are listed in data_names list or not.

**Comment by nuernbergerc** [comment]
@mrainers is there any progress to solve this issue?

**Comment by mrainers** [comment]
I didn't wrote the export function, so it didn't come to my mind that I might be in charge.

**Comment by nuernbergerc** [comment]
do you have an idea how to solve this?

**Comment by mrainers** [comment]
Yes, see section "Additional Information" in the Issue description. I would prefer solution idea 2.

**Comment by nuernbergerc** [comment]
could you do the change in the code?
i do not have any preferences as long as it works

**Comment by mrainers** [comment]
I can have a look at it next week.

**Comment by nuernbergerc** [comment]
thanks

**Comment by mrainers** [comment]
Fix is uploaded and merge request created.

The fix exports all named data frames from the data object (Usually all objects in the data list should have a name). If an unnamed data frame is found in the data object, the write_tsExport function will print a warning.
