### ISSUE TITLE
primary_coding_suep() changes variable types from certain variables from original data set without further notice

### ISSUE THREAD

**Issue by mrainers** [nukleus-ecu/epicodr#18]
### Description

When running primary_coding_suep() on the suep data set, then the variables "brs_2"," brs_4" and "brs_6" from the "promext" table where changed from double to integer type and their attributes such as variable label is stripped away.

Other variables might be affected as well. Didn't check the whole data set.

### Steps to Reproduce

1. load suep data: `suep_data <- read_tsExport(DATA_SUEP_DIR, decimal = ",")`
2. check structure of brs_2 variable: `str(suep_data$promext$brs_2)`
3. run primary_coding_suep(): `suep_data_primary_coded <- primary_coding_suep(suep_data)`
4. check structure of brs_2 variable in primary coded data set:  `str(suep_data_primary_coded$promext$brs_2)`

**Expected behavior**

The original variables should stay untouched by the primary_coding_suep() function. Only new variables should be added.

**Actual behavior**

The data type of the above mentioned variables is changed to integer and the attributes where stripped away, which is a clear sign that those variables have been overwritten by the primary_coding_function() without informing the user.

**Reproducibility**

The Issue can be reproduced reliably.

### Versions

R version 4.0.3 (2020-10-10)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 10 x64 (build 19045)

attached packages:
 [1] epicodr_1.0.0   forcats_0.5.2   stringr_1.4.0   dplyr_1.1.0     purrr_1.0.1    
 [6] readr_2.1.2     tidyr_1.2.0     tibble_3.1.6    ggplot2_3.4.1   tidyverse_1.3.2

**Comment by nuernbergerc** [comment]
some brs variables needed recoding using the function in line 306 in primary-coding-suep.R, so they were overwritten
what would you suggest? create new recoded variables? or would it help to just remove as.integer from the function?

**Comment by mrainers** [comment]
I would suggest to create new temporary variables that can be used for the computation and thrown away afterwards.
