### ISSUE TITLE
The data_primary_coded_suep() function takes several minutes for computation.

### ISSUE THREAD

**Issue by mrainers** [nukleus-ecu/epicodr#19]
For test purposes I ran primary_coding_suep() on the data set "tsExport_Testdata_SUEP_2022-06-27". This data set contains 214 patients and probably lots of missing values. However when I run data_primary_coded_suep() on the data, the process takes several minutes and it feels like R is hanging. But with enough patience, though, the process eventually finishes and creates the primary coded data. 

Can you confirm this with other SÜP data sets?
Is it possible to optimize the calculations, so it's running faster?

I tested it with epicodr git version 0.16.0 from Fri Mar 31 19:30:52 2023 +0200

**Comment by nuernbergerc** [comment]
yeah that takes long
but it computes all primary coding functions at once. WHO-Scale itselfe takes some time

Olga and I thought about this issue. We will try to find a solution
