### ISSUE TITLE
Change the default decimal sign option in read_tsExport to "," instead of ".", because this is default export format. 

### ISSUE THREAD

**Issue by mrainers** [nukleus-ecu/epicodr#2]
*This is a copy of Issue https://github.com/nukleus-ecu/napkon-ecu/issues/70 because it is present in both packages.*

I noticed, that for some reasons the the default read export option for the decimal sign is a dot. That might result that variables with a comma in it are treated as characters instead of doubles when the data is read into R. Because the default option for secutrial exports that is used by the transferstelle is comma as a decimal, this should be mirrored in the default read option for read_tsExport function.

**Comment by nuernbergerc** [comment]
change has been merged with main branch
