### ISSUE TITLE
Items in Lookup-List should be ordered by their appearance in the data and not alphabeticly

### ISSUE THREAD

**Issue by mrainers** [nukleus-ecu/epicodr#3]
The tsExport data object contains lookup lists for variable labels, value labels and date variables. They do their Job when it comes to adding labels etc. to the data. However if I, as a human want to check out the lookup lists by my self und compare them with the data it would be helpfull if their item would be sorted in the same order as they appear in the data and not alphabeticly by their name.

**Comment by mrainers** [comment]
In der Funktion "factorize_tsExport_table" erzeugen die folgenden Zeilen einen Fehler, wenn die Lookup-Tabelle eine andere Reihenfolge hat, was mich sehr verwundert, denn eigentlich sollte das nichts miteinander zu tun haben.

# Remove value labels from the original variable, so the numeric values are kept as is when exporting to e.g. spss
.data <- .data %>% 
mutate(across(where(is.labelled) & !ends_with(".factor"), 
haven::zap_labels)) 

Ich werde das mal untersuchen.

Andere Frage in Bezug auf den Code. Mit Hinblick auf den Export nach SPSS sind diese Codezeilen sogar kontraproduktiv, denn sie sorgen gerade dafür, dass bei einem SPSS-Export die Variablen-Labels nicht mehr da sind. Gibt es andere Gründe, warum die Labels entfernt wurden? Sonst würde ich diese Code-Zeilen entfernen.

**Comment by mrainers** [comment]
lol, der Unterschied war, dass ich einmal die Funktion aus dem epicodr-package verwendet hatte, dann aber zum Ändern und Testen die Funktion in den lokalen Workspace  geladen hatte. In diesem wurde aber die function `is.labelled` nicht erkannt, weil ich das Paket "haven" nicht geladen hatte. Die Code-Stelle sollte also wirklich keine Probleme mit der Lookup-Liste haben. Aber eine Paket-Adressierung vor die is.labelled funktion zu packen ist saver.

**Comment by mrainers** [comment]
Dennoch bleibt die Frage, was ist der konkrete Nutzen davon die Wertelabels zu entfernen? Denn für den Export nach SPSS muss ich sie ja erneut wieder hinzufügen.

**Comment by nuernbergerc** [comment]
ich glaube der Hintergrund war, dass sonst die Variablen doppelt drinnen sind, also einmal numerisch und einmal gelabelt, was man sich in SPSS ja sparen kann
bin mir aber auch nicht sicher

**Comment by mrainers** [comment]
Das klingt nicht schlüssig. Bei einem SPSS-Export mit dem "haven"-Package werden die gelabelten numerischen Variablen auch entsprechend exportiert. Also als numerische Variablen + ihre Label-Informationen. Die Labels gehen natürlich verloren, wenn man die Labels mit `haven::zap_labels` entfernt. Daher ist ein solcher Schritt ein großer Nachteil für den Export nach SPSS. Variablen sind allenfalls deswegen doppelt weil wir beim Einlesen noch zusätzlich .factor-Variablen erzeugt haben. Diese .factor-Variablen sollten daher sinnvollerweise vor dem Export aus den Daten gelöscht werden. Auch aus diesen Variablen werden in SPSS gelabelte numerische Variablen erzeugt. Aber anscheinend kümmert sich die Exportfunktion nicht um die original-Levels (numerischen Werte), sondern führt offenbar eine Art `autorecode` durch und erzeugt neue numerische Werte, die dann vom original-Secutrial-Export abweichen.

**Comment by nuernbergerc** [comment]
wie gesagt, ich war mir da auch nicht sicher, wieso das erfolgt ist. Evtl. weiß @miljukov-o da mehr
generell sollten die Labels in SPSS enthalten sein, aber die Faktor-Variablen (... .factor) nicht mehr auftauchen. Mit der Export-Funktion kenne ich mich nicht aus. Wenn der Code deiner Meinung nach nicht notwendig/kontraproduktiv ist, kann der von meiner Seite aus auch raus.

**Comment by miljukov-o** [comment]
> In der Funktion "factorize_tsExport_table" erzeugen die folgenden Zeilen einen Fehler, wenn die Lookup-Tabelle eine andere Reihenfolge hat, was mich sehr verwundert, denn eigentlich sollte das nichts miteinander zu tun haben.
> 
> ```
> # Remove value labels from the original variable, so the numeric values are kept as is when exporting to e.g. spss
> .data <- .data %>% 
> mutate(across(where(is.labelled) & !ends_with(".factor"), 
> haven::zap_labels)) 
> ```
> 
> Ich werde das mal untersuchen.
> 
> Andere Frage in Bezug auf den Code. Mit Hinblick auf den Export nach SPSS sind diese Codezeilen sogar kontraproduktiv, denn sie sorgen gerade dafür, dass bei einem SPSS-Export die Variablen-Labels nicht mehr da sind. Gibt es andere Gründe, warum die Labels entfernt wurden? Sonst würde ich diese Code-Zeilen entfernen.

"factorize_tsExport_table" kommt von dir @mrainers, glaube ich. Du hast damals die secuTrialR Funktionen für die Transferstellen Exporte angepasst.

**Comment by miljukov-o** [comment]
> Das klingt nicht schlüssig. Bei einem SPSS-Export mit dem "haven"-Package werden die gelabelten numerischen Variablen auch entsprechend exportiert. Also als numerische Variablen + ihre Label-Informationen. Die Labels gehen natürlich verloren, wenn man die Labels mit `haven::zap_labels` entfernt. Daher ist ein solcher Schritt ein großer Nachteil für den Export nach SPSS, der sich aber beheben lässt, wenn man die labels kurz vor dem Export wieder hinzufügt. Variablen sind allenfalls deswegen doppelt weil wir beim Einlesen noch zusätzlich .factor-Variablen erzeugt haben. Diese .factor-Variablen sollten daher sinnvollerweise vor dem Export aus den Daten gelöscht werden. Auch aus diesen Variablen werden in SPSS gelabelte numerische Variablen erzeugt. Aber anscheinend kümmert sich die Exportfunktion nicht um die original-Levels (numerischen Werte), sondern führt offenbar eine Art `autorecode` durch und erzeugt neue numerische Werte, die dann vom original-Secutrial-Export abweichen.

Ansonsten haben wir von dem secuTrialR Package die Export- bzw. write Funktionen übernommen. Dabei werden die originalen, unverarbeiteten Variablen sowie deren neue erzeugte Faktor- bzw. Datums-Varianten exportiert. Der Sinn dabei ist, dass man eben für den Fall der Fälle die Originale hat, aber mit der formatierten Variante Analysen macht.
