### ISSUE TITLE
Ungültige Daten im Transferstellenexport in Wiederholungsgruppen-Dateien

### ISSUE THREAD

**Issue by nuernbergerc** [nukleus-ecu/epicodr#9]
## von der TO kam folgender Hinweis:

**Der an Sie herausgegebene Datensatz enthält leider ungültige Einträge in den Wiederholungsgruppendateien**

(die Dateien beginnen mit "e_"). Hierbei handelt es sich Einträge, die fehlerhaft angelegt wurden und darum in Secutrial "versteckt", und ggf. neu angelegt wurden. Auch wenn diese Daten in der Datenanzeige von Secutrial nicht sichtbar sind, werden sie dennoch, je nach Exporteinstellung, von Secutrial exportiert. Sie sind dann im Secutrial-Export mit der Variable "mnphide = 1" gekennzeichnet. Weil es sich hierbei um fehlerhafte Eingaben handelt, haben wir in der Transferstelle eine Routine geschrieben die diese Einträge standardmäßig aus den Daten löscht, bevor wir sie herausgeben. (Die Variable „mnphide“, wird nach dieser Routine aus dem Datensatz entfernt, weil sie dann überall NA ist, und keine Aussagekraft mehr hat.) Dabei haben wir jedoch leider übersehen, dass die Wiederholungsgruppendateien keine Variable "mnphide" haben über die wir die versteckten Einträge hätten filtern können. Dafür hätten wir sie vorher mit den dazugehörigen Hauptformular-Einträgen verknüpfen müssen. Und so kam es, dass diese versteckten Einträge im Herausgabeexport enthalten sind.

_Wie kann ich die versteckten/ungültigen Einträge in meinen Daten erkennen?_

Die Wiederholungsgruppen-Dateien enthalten eine Variable namens "main_form". Ist hier der Eintrag leer, handelt es sich um einen versteckten bzw. ungültigen Eintrag.

Der Hintergrund ist folgender: Diese Variable wurde von der Transferstelle eingefügt um die Verknüpfung der Wiederholungsgruppendaten mit den dazugehörigen Hauptformulardaten zu erleichtern. Da aber in einem vorherigen Schritt bei den Hauptformularen die versteckten Einträge entfernt wurden, konnte der entsprechende Fall in der Wiederholungsgruppe nicht mehr mit einem Fall aus dem Hauptformular gematcht werden. Daher ist bei diesen Fällen die Variable "main_form" leer geblieben.

_In R können Sie wie folgt prüfen, ob eine/welche Tabellen mind. einen versteckten/ungültigen Eintrag hat:_

library(dplyr)
library(purrr)

Einzeltabelle am Beispiel von e_symptom:
Enthält e_symptom ungültige Einträge?
   e_symptom$main_form %>% is.na() %>% any()

Alle Tabellen die mit dem epicodr-Paket geladen wurden bzw. sich in einer gemeinsamen Liste befinden:
Welche Tabellen enthalten ungültige Einträge?
   data %>%
   keep(~ "main_form" %in% names(.) && (.x$main_form %>% is.na() %>% any())) %>%
   names()

_Wie kann ich die versteckten/ungültigen Einträge löschen?_

Falls Sie mit R arbeiten können Sie mit dem folgenden Code die Einträge aus einer bestimmten Tabelle löschen bzw. aus allen Tabellen , falls Sie die Daten mit dem epicodr-Paket eingelesen haben oder die Tabellen

ganz allgemein in einer gemeinsamen Liste namens „data“ gespeichert sind:

Einzeltabelle am Beispiel von e_symptom:
Alle ungültigen Einträge aus e_symptom löschen.
   e_symptom <- e_symptom %>% 
   filter(!is.na(main_form))

Alle Tabellen die mit dem epicodr-Paket geladen wurden bzw. sich in einer gemeinsamen Liste befinden:
Alle ungültigen Einträge aus allen Wiederholungsgruppentabellen löschen.
   data <- data %>%
   modify_if(~ "main_form" %in% names(.x), ~ .x %>% filter(!is.na(main_form)))

**Comment by nuernbergerc** [comment]
@mrainers sollte das in den epicodr eingebaut werden? wenn ja, an welcher Stelle? bzw. könntest du das direkt übernehmen, bitte.

**Comment by nuernbergerc** [comment]
Olga hatte noch folgendes angemerkt:
"Beim Filtern auf Review A kann ja das gleiche Problem auftreten, da die Variable für Review A in der Tabelle des Hauptformulars steckt. Hier besteht soweit keine Gefahr, oder?"
Besteht hier auch noch Handlungsbedarf?

**Comment by mrainers** [comment]
Ich habe überprüft, welche Herausgaben das betrifft. Es sind nur 7. Die entsprechenden Antragsteller sind mit der oben stehenden Mail informiert. Der Bug in in unserem Herausgabeskript ist bereits gefixt. Daher sehe ich kein Handlungsbedarf für das Epicodr-Paket. 

Die Mail habe ich an die ECU lediglich zur Kenntnisname geschickt. Falls es euch hilft, kann ich euch aber noch die Liste der Betroffenen Herausgaben schicken.

**Comment by mrainers** [comment]
> Olga hatte noch folgendes angemerkt: "Beim Filtern auf Review A kann ja das gleiche Problem auftreten, da die Variable für Review A in der Tabelle des Hauptformulars steckt. Hier besteht soweit keine Gefahr, oder?" Besteht hier auch noch Handlungsbedarf?

Genau, aber das hatten wir beim Review-A filtern rechtzeitig gesehen und entsprechend berücksichtigt. Von daher ist auch hier kein Handlungsbedarf.

**Comment by nuernbergerc** [comment]
> 

alles klar. Danke für die Info und das Beheben des Problems
Dann schließe ich den Issue gleich wieder.
